### PR TITLE
renamed gptxdata

### PR DESCRIPTION
**Pull request by fromm-m**

### CODE REVIEW

**Comment by janEbert** [comment]
With `gptx_data` existing again (and it seems to still include tokenizers), what is the way forward?

**Comment by fromm-m** [comment]
> With `gptx_data` existing again (and it seems to still include tokenizers), what is the way forward?

gptx_data is now only for the data preprocessing pipeline, it is currently undergoing a major cleanup

-> gptx_tokenizer will be the link for megatron-lm and the respective tokenizers

**Comment by janEbert** [comment]
Sounds good, I'd like to make sure other repos such as the setup one also have this change before merging.

**Comment by fromm-m** [comment]
> Sounds good, I'd like to make sure other repos such as the setup one also have this change before merging.

Thanks Jan!
Would be good to have it soonish as people are already hosting our models in some places and they still require our whole data preprocessing code ;)

**Pull request merged**
